In [26]:
import pandas as pd

## Reading Data

In [27]:
df=pd.read_csv("data.csv")

In [28]:
df.head()

fever  bodypain  age  runnyNose  breathHardness  sorethroat  drycough  \
0     99         1   44          0               1           1         1   
1    102         1   10          0               0           1         1   
2    104         1   93          0              -1           1         1   
3    100         1   76          0              -1           0         0   
4    102         0   72          0               1           0         1   

   Infection  
0          1  
1          1  
2          0  
3          0  
4          1

In [29]:
df.tail()

fever  bodypain  age  runnyNose  breathHardness  sorethroat  drycough  \
984     99         0   16          1              -1           0         1   
985    104         0   83          1              -1           1         1   
986    103         0   82          0              -1           0         0   
987    103         0   42          1               1           0         0   
988    104         0   61          0               0           1         0   

     Infection  
984          0  
985          0  
986          1  
987          0  
988          0

In [30]:
df.info()|

SyntaxError: invalid syntax (<ipython-input-30-2bec8f963757>, line 1)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fever           989 non-null    int64
 1   bodypain        989 non-null    int64
 2   age             989 non-null    int64
 3   runnyNose       989 non-null    int64
 4   breathHardness  989 non-null    int64
 5   sorethroat      989 non-null    int64
 6   drycough        989 non-null    int64
 7   Infection       989 non-null    int64
dtypes: int64(8)
memory usage: 61.9 KB


In [32]:
df['fever'].value_counts()

105    158
103    158
101    146
100    137
102    136
99     133
104    121
Name: fever, dtype: int64

In [33]:
df['breathHardness'].value_counts()

 0    360
-1    322
 1    307
Name: breathHardness, dtype: int64

In [34]:
df['drycough'].value_counts()

1    497
0    492
Name: drycough, dtype: int64

In [35]:
df.describe()

fever    bodypain         age   runnyNose  breathHardness  \
count  989.000000  989.000000  989.000000  989.000000      989.000000   
mean   102.055612    0.516684   50.457027    0.501517       -0.015167   
std      1.999985    0.499974   29.066053    0.500251        0.797753   
min     99.000000    0.000000    1.000000    0.000000       -1.000000   
25%    100.000000    0.000000   25.000000    0.000000       -1.000000   
50%    102.000000    1.000000   50.000000    1.000000        0.000000   
75%    104.000000    1.000000   76.000000    1.000000        1.000000   
max    105.000000    1.000000  100.000000    1.000000        1.000000   

       sorethroat    drycough   Infection  
count  989.000000  989.000000  989.000000  
mean     0.490394    0.502528    0.509606  
std      0.500161    0.500247    0.500161  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    1.000000    1.000000  
75%      1.000000    1.000000    1.000000  
max      1.000000    1.000000    1.000000

## Train Test Splitting

In [36]:
import numpy as np

In [37]:
def ds_split(data, ratio):
    np.random.seed(42)
    shuffeld = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffeld[:test_set_size]
    train_indices = shuffeld[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]


In [38]:
np.random.permutation(10)

array([1, 0, 7, 6, 8, 3, 2, 9, 4, 5])

In [39]:
train,test = ds_split(df, 0.2)

In [40]:
train

fever  bodypain  age  runnyNose  breathHardness  sorethroat  drycough  \
237    101         1   17          0               1           1         1   
753    101         1   90          0               0           1         1   
215     99         0   30          0              -1           0         0   
294    101         0   61          0               1           1         0   
49     105         0   86          0               0           0         0   
..     ...       ...  ...        ...             ...         ...       ...   
106    104         0   18          0               0           1         0   
270    102         0   90          0              -1           0         1   
860    103         1   40          0              -1           0         0   
435    103         1   72          0              -1           1         0   
102    100         0   74          0               0           1         1   

     Infection  
237          1  
753          0  
215          0  
294          1  
49           0  
..         ...  
106          1  
270          1  
860          0  
435          1  
102          0  

[792 rows x 8 columns]

In [41]:
df.tail()


fever  bodypain  age  runnyNose  breathHardness  sorethroat  drycough  \
984     99         0   16          1              -1           0         1   
985    104         0   83          1              -1           1         1   
986    103         0   82          0              -1           0         0   
987    103         0   42          1               1           0         0   
988    104         0   61          0               0           1         0   

     Infection  
984          0  
985          0  
986          1  
987          0  
988          0

In [42]:
X_train = train[['fever','bodypain','age','runnyNose','breathHardness','sorethroat','drycough']].to_numpy()

In [43]:
X_train

array([[101,   1,  17, ...,   1,   1,   1],
       [101,   1,  90, ...,   0,   1,   1],
       [ 99,   0,  30, ...,  -1,   0,   0],
       ...,
       [103,   1,  40, ...,  -1,   0,   0],
       [103,   1,  72, ...,  -1,   1,   0],
       [100,   0,  74, ...,   0,   1,   1]], dtype=int64)

In [44]:
X_train = train[['fever','bodypain','age','runnyNose','breathHardness','sorethroat','drycough']].to_numpy()
X_test = test[['fever','bodypain','age','runnyNose','breathHardness','sorethroat','drycough']].to_numpy()

In [45]:
Y_train = train[['Infection']].to_numpy().reshape(792 ,)
Y_test = test[['Infection']].to_numpy().reshape(197 ,)

In [46]:
Y_test

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1],
      dtype=int64)

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
input_feature = [100,0,22,1,0,0,1]
infprob = clf.predict_proba([input_feature])[0][1]

In [50]:
infprob

0.4902466127884839